# Generated by Django 5.0.6 on 2024-11-20 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Taxpayer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='taxpayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to='Taxpayer.taxpayerprofile'),
        ),
    ]
